version: '3.8'
services:
  bot:
    container_name: crBotDev
    image: countingman:cm2Dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    links:
      - mongo
  mongo:
    container_name: crmongo
    image: mongo
    env_file:
      - ./.env
    volumes:
      - ./data:/data/db
    command: mongod --port 27024
    ports:
      - '27024:27024'
